######################################################################
# Automatically generated by qmake (2.01a) Sun Sep 11 20:44:07 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
