######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 9 23:01:46 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../model.h ../linear.h ../tron.h ../blas/*.h ../controller.h ../viewbase.h
SOURCES += main.cpp ../model.cpp ../linear.cpp ../tron.cpp ../blas/*.c ../controller.cpp 


 wince*: {
    DEPLOYMENT_PLUGIN += qjpeg qmng qgif
 }
